### ISSUE TITLE
Venue resources

### ISSUE THREAD

**Issue by sveredyuk** [pivorakmeetup/pivorak-web-app#10]
1. CRUD [:name, :address, :maps_url, :description]
2. `Venue has_many :events`
3. `Event belongs_to :venue, optional: true`

**Comment by illia108** [comment]
Hi. I would like to implement this feature.

**Comment by sveredyuk** [comment]
@illia108 Good luck bro! Just check how I implement Events Resource and make the same. Also I made changes to Events (with authorization), PR will be very soon.

**Comment by sveredyuk** [comment]
@illia108 Join our slack chat [pivorak-slack.herokuapp.com](pivorak-slack.herokuapp.com) We have special #pivorak-web-app channel for contributors.

**Comment by sveredyuk** [comment]
@illia108 FIY https://github.com/pivorakmeetup/pivorak-web-app/issues/23
