### ISSUE TITLE
Admin create  other admin

### ISSUE THREAD

**Issue by sveredyuk** [pivorakmeetup/pivorak-web-app#138]
Add admin checkbox to Edit Member form (/admin/members/:id/edit)

**Comment by denys-medynskyi** [comment]
I am not sure about checkbox. 
What about create admin form ? 
I want to ask Oxana or Anna what will be more useful for them.

**Comment by sveredyuk** [comment]
@denysmedynskyi i think simple checkbox for LEAN will be enough
