### ISSUE TITLE
Rewrite admin area to SemanticUI

### ISSUE THREAD

**Issue by sveredyuk** [pivorakmeetup/pivorak-web-app#146]
Bootsrap4 sucks... looks ugly and poor design of tools force me rewrite UI to  http://semantic-ui.com/ with https://github.com/doabit/semantic-ui-sass

**Comment by oookli** [comment]
@sveredyuk I can help you with it, how you think?

**Comment by sveredyuk** [comment]
@oookli will be great. I already started. Will rewrite one resource, and that you can help with other resources.
