### ISSUE TITLE
Talk discussion system

### ISSUE THREAD

**Issue by pivorak** [pivorakmeetup/pivorak-web-app#148]
было бы здорово иметь какую-то площадку в онлайне, вроде небольшого форума, где можно было бы обсуждать доклады после пиворака
желающие могли бы задать там вопросы, докладчик мог бы ответить на них, исправить неточности которые были во время выступления, поделиться материалом. да и вообще собрать фидбек, улучшить доклад, и т.д.
существует такая штука как http://www.discourse.org/ он опен сорсный

***
Можна діскурс або щось подібне додати до сторінки Події - щоб люди могли перепитати що де коли (як в мітапі німець питав) і додати до сторінки де буде Відео - щоб могли задавати питання до відео.
Наразі так, як маєте ідеї, де ще б доцільно його мати, кажіть

**Comment by lavriv92** [comment]
Хороша ідея приасайнити обговорення до івент,  доповіді, щоб там люди задавали питання і обговорювали

**Comment by sveredyuk** [comment]
@lavriv92 Та вот думаю, шо свій engine буде простіше написати, ніж щось інтегроувати.

**Comment by lavriv92** [comment]
@sveredyuk Aбо так, мабуть справді краще так
