### ISSUE TITLE
Add sitemap

### ISSUE THREAD

**Issue by sveredyuk** [pivorakmeetup/pivorak-web-app#155]

**Comment by denys-medynskyi** [comment]
do we need it for SEO ?

**Comment by sveredyuk** [comment]
Ofc

**Comment by denys-medynskyi** [comment]
there is [article in rubyweekly](https://www.sitepoint.com/start-your-seo-right-with-sitemaps-on-rails/?utm_source=rubyweekly&utm_medium=email). Is it good for sitemap implementation ?

**Comment by sveredyuk** [comment]
Yes.
