### ISSUE TITLE
Photogallery url for event

### ISSUE THREAD

**Issue by sveredyuk** [pivorakmeetup/pivorak-web-app#168]
Add `photogallery_url` to Event. Link from Facebook.
At event page iframe for facebook gallery

**Comment by denys-medynskyi** [comment]
I suggest to use `gallery_url` instead of `photogallery_url`, because the last one seems incorrect for me

**Comment by denys-medynskyi** [comment]
according to [docs](https://developers.facebook.com/docs/plugins/embedded-posts) there is no easy way to embed facebook photos, so I need fetch them using API and I need pivorak facebook credentials.
other option will be to not use iframes and just use link to facebook photo album.
what do you think @sveredyuk ?

**Comment by sveredyuk** [comment]
@denysmedynskyi Ok. Merge, push.

**Comment by denys-medynskyi** [comment]
There easy way to embed post with iframe.
It will look like this: 
http://collabshot.com/show/0Yx0yf
What do you think @sveredyuk ?

**Comment by sveredyuk** [comment]
@denysmedynskyi good enough.
