### ISSUE TITLE
Beautify admin home page

### ISSUE THREAD

**Issue by sveredyuk** [pivorakmeetup/pivorak-web-app#173]
Admin home page is too bored now. What about pretty navigation menu with awesome icons ?

<img width="836" alt="2017-02-03 15 40 49" src="https://cloud.githubusercontent.com/assets/5221643/22593473/4da69450-ea27-11e6-96c4-464e7a8be6f5.png">

**Comment by sergiy-koshoviy** [comment]
@sveredyuk  What do you want to use for UI? or only custom (js and sass)?

**Comment by denys281** [comment]
@sveredyuk  I could offer only this: http://www.semantickit.com/themes/11-responsive-dashboard-theme/preview ;-)

**Comment by sveredyuk** [comment]
@denys281 Let's try.
Out main models now are:
1) Events (group by status)
2) Members (would be nice to show how count increase (last week, month)

Pretty enough for start.

**Comment by denys281** [comment]
@sveredyuk 

It is not free template  (12$): http://www.semantickit.com/categories/admin-dashboard. But actually we could copy it...

I also try to find something for free but semantic not so popular as bootstrap :( 

I found something like that: 
<img width="1262" alt="screenshot 2017-02-13 23 21 09" src="https://cloud.githubusercontent.com/assets/754467/22903931/24ef99f2-f243-11e6-8f46-18b7a0a2cff3.png">

Or we could do something else.

**Comment by sveredyuk** [comment]
@denys281 In fact, we need the only dashboard. Not necessary buy or take the whole theme (yet). 
Try to do your best. I am sure it will be fine.

**Comment by denys281** [comment]
@sveredyuk Something like that:

![screen shot 2017-02-14 at 5 34 43 pm](https://cloud.githubusercontent.com/assets/754467/22935663/e782ec10-f2db-11e6-89f9-183bc7da160f.png)


![screen shot 2017-02-14 at 5 31 27 pm](https://cloud.githubusercontent.com/assets/754467/22935522/7d5829cc-f2db-11e6-9527-13742f1ce608.png)

We also add more graphs :)

**Comment by denys281** [comment]
@sveredyuk did you have chance to check screenshots?

**Comment by sveredyuk** [comment]
@denys281 Yes, ofc. Looks awesome.
Does it ready for merge ?

**Comment by denys281** [comment]
@sveredyuk no, I should move some counts and group to finders.

**Comment by sveredyuk** [comment]
@denys281 check my comments at MR
