### ISSUE TITLE
Payment gateway

### ISSUE THREAD

**Issue by sveredyuk** [pivorakmeetup/pivorak-web-app#176]
Add Liqpay as payment gateway and setup is as default for Donations.

**Comment by sergiy-koshoviy** [comment]
https://github.com/pivorakmeetup/pivorak-web-app/compare/176-payment-gateway

проблеми з локальною перевіркою що б liqpay було куди слати реквести підключив 
ngrok і тоді до сервака можна було отримувати доступ за адресою http://e4a61f3a.ngrok.io
але коли прилітає реквест то апп падає девайс каже що по даному токену доступні лише локальні адреси 127.0.0.1 і тд

<img width="1019" alt="screen shot 2017-02-18 at 6 43 22 pm" src="https://cloud.githubusercontent.com/assets/5254946/23097910/b99bb210-f60e-11e6-9628-67b0997163dc.png">

**Comment by sergiy-koshoviy** [comment]
On hold. Waiting for result of problem with government.
