### ISSUE TITLE
Trailblazer2

### ISSUE THREAD

**Issue by sveredyuk** [pivorakmeetup/pivorak-web-app#179]
I clearly recognize that for start RailsWay is pretty enough.
But develop the project to something more very soon became painful.

So, what about to move all processing code to **TRB2** -> http://trailblazer.to/

- Services -> Operations
- Views -> Cells
- Validations - Contracts (dry-validation)
- Policy -> Policy
- Custom code -> lib under concepts

From rails left only:
- Router
- Controllers (only call operations)
- Models (only persist)
- Engines (yes, next step will be cut all this into small engines)

Decision move to TRB must be collective

**Comment by kushniryb** [comment]
Count me in, I'm sure it'll look much more better with TRB despite the fact that v2.0 is kinda disappointing... :disappointed:

**Comment by sveredyuk** [comment]
@kushniryb why disappointing? A new operation is a great tool for building solid business rules. Maybe you need discover it more.

**Comment by kushniryb** [comment]
Preserving objects in hash with string keys is just ridiculous to be honest
Nevertheless - still better than typical Rails way
When do we start?

**Comment by sveredyuk** [comment]
@kushniryb state object principle. Better than uncontrolled ivars... a lot of mutating ivars.

Start after other contributors will agree and after 1.0 release.

**Comment by denys281** [comment]
@sveredyuk  I think it depends about your plans for future. In case after 1.0 release you plan to add a lot of serious and huge features than yes.

**Comment by sveredyuk** [comment]
My **"BIG PLAN"** is to create excellent OSS product that can be constructed from a lot of different small modules.  

- Core: User, authentication (can be extended any you want)
- Events: Event, Talks (extend Core)
- Taxonomy / Groups (extend Core)
- Venues (extend Events)
- Community: Members, VisitReuquest (extend  Events)
- Blog (extend Core)
- Donations (extend Core)
- Goals (extend Donations)
- Email service (extend Community)
- Pages (extend Core)
- Friends (extend Core)

So... if you are director of the local community (any language or technology or not event technology), just install core, choose modules what you need (as extensions).

Frontend for all this stuff could be custom or we can provide some sandbox with theming.

Strongly inspired by [Spree](https://spreecommerce.com/)

**Comment by sveredyuk** [comment]
In future, this can be CMS system. Just pick modules that you need.

But this requires a lot of non-coding work. Documents and so on.

**Comment by denys281** [comment]
Then move to tb2 seems reasonable step.
