### ISSUE TITLE
DEPRECATION WARNINGS

### ISSUE THREAD

**Issue by denys281** [pivorakmeetup/pivorak-web-app#182]
During `rspec` in some places you could see: 

`DEPRECATION WARNING: before_filter is deprecated and will be removed in Rails 5.1. Use before_action instead.`

During `rake db:seed` in some places you could see: 

`DEPRECATION WARNING: Passing a class as a value in an Active Record query is deprecated and will be removed. Pass a string instead.`

**Comment by denys-medynskyi** [comment]
@denys281 I remembered that we were Rails Girls coaches in Ternopil'. 
Glad to see familiar faces)

**Comment by sveredyuk** [comment]
This deprecation calls from semantic-ui-rails gem. 
They use before_filter for set breadcrumbs I will suggest PR for them with fix.

https://github.com/doabit/semantic-ui-sass/blob/119c166f490682c40fe0274f7d3ccb86e384fa0a/lib/semantic/ui/sass/breadcrumbs.rb#L13

Open PR:
https://github.com/doabit/semantic-ui-sass/pull/99

**Comment by denys281** [comment]
@denysmedynskyi  Yes, we where ;-)

@sveredyuk  Do you have some coding tasks for me?)

**Comment by sveredyuk** [comment]
@denys281 for 1.0 we almost have done with the backend. 
The only frontend left. This Saturday we will have a meeting and decide what to do next.

**Comment by sveredyuk** [comment]
https://github.com/doabit/semantic-ui-sass/pull/99

**Comment by denys281** [comment]
@sveredyuk  In #246 I updated gem so it seems that all warnings fixed.
