### ISSUE TITLE
Topic Voting

### ISSUE THREAD

**Issue by sveredyuk** [pivorakmeetup/pivorak-web-app#199]
- Any Member could suggest topic for potential pivorak's talk -> SuggestedTopic
- Admin moderate suggestions and publish/decline topics for the voting
- Members vote for each topic once per week
- New week - new votes possibilities for all members
- Admin can mark suggest_topic as "go to preparing" and it went away from the list

**Comment by kushniryb** [comment]
@sveredyuk Could you please provide more details?

**Comment by sveredyuk** [comment]
@kushniryb good luck, bro :)

**Comment by sveredyuk** [comment]
@kushniryb Any updates?

**Comment by kushniryb** [comment]
@sveredyuk 
WIP at the moment :|
What's a due date?

**Comment by sveredyuk** [comment]
No deadlines) Just ask to know if I should push our designer to produce mockups for this feature.
