### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by sveredyuk** [pivorakmeetup/pivorak-web-app#21]
Donations are important! More important than donations are goals which cover by donations.

We need **Goals** resource `[title, description, amount]` and only admin can manage goals.
The regular member can only view it and make donations.

**Donations** through `Stripe` in `UAH`.
Donations could be assigned to user or anonymous if user logged in and checkbox "anonymous donation"

App receives all payments (donations) and register them. 
Also admin can add payment as cash.

Progress bar at goal page shows how much UAH/percents collect/left.

When expected amount == total donations per goal -> goal become **achieved**!
Yeahh.... pfpfpfpf... salute!

**Comment by kushniryb** [comment]
@sveredyuk
Almost done with this issue - a few questions

1. So as far as I understood - no progress bar for now, correct?

2. Why do we need to allow anonymous donations? Not that it's hard to implement, but what's the point, considering only logged in users can make a donation?

**Comment by sveredyuk** [comment]
@kushniryb 

1. Yes, no progress bar need yet. This will be task for @yuriichaban 

2. Anonymously - It's common practice in donations. Not only logged in user can make donations. Logic simple: if not logged in user donate - it's anonymous and also logged in user was logged but checked box "anonymous donation". Only if user was logged in and not checked "anonymous" - this kind of donation are public.

**Comment by kushniryb** [comment]
Can we close this @sveredyuk ?

**Comment by sveredyuk** [comment]
@kushniryb Ofc. Press close issue
