### ISSUE TITLE
Better errors style

### ISSUE THREAD

**Issue by sveredyuk** [pivorakmeetup/pivorak-web-app#220]
Hope we could provide better design for has-errors field
<img width="336" alt="2017-03-09 21 56 52" src="https://cloud.githubusercontent.com/assets/5221643/23768050/64a6d582-0513-11e7-8d09-6f49423f14c9.png">

**Comment by pbilyk** [comment]
I can take it. Thinking about something along the lines of this screenshot.
<img width="318" alt="screen shot 2017-04-08 at 9 58 50 pm" src="https://cloud.githubusercontent.com/assets/1926978/24831673/f4b2aaca-1ca6-11e7-9318-03d0259f1c4d.png">

**Comment by denys-medynskyi** [comment]
https://github.com/pivorakmeetup/pivorak-web-app/pull/308
