### ISSUE TITLE
Different event attend flash message

### ISSUE THREAD

**Issue by sveredyuk** [pivorakmeetup/pivorak-web-app#235]
For verified members and newbies members

**Comment by denys-medynskyi** [comment]
I don't get. What do you mean ?

**Comment by sveredyuk** [comment]
@denysmedynskyi Verified members after attend should see message about "auto-approve" and newbies should see message that "We will review your request and inform you soon"

Now both of them see same message.

**Comment by sveredyuk** [comment]
@denysmedynskyi you or me ?

**Comment by sveredyuk** [comment]
@denysmedynskyi done ?

**Comment by sveredyuk** [comment]
Done
