### ISSUE TITLE
User email bug

### ISSUE THREAD

**Issue by sveredyuk** [pivorakmeetup/pivorak-web-app#238]
the user now could register with his email and email with ambitious symbols

ann.golovchenko@gmail.com
ann.golovchenko+1@gmail.com

Will create two accounts but send all emails only to ann.golovchenko@gmail.com

Wtf devise ?

**Comment by sveredyuk** [comment]
Hello @denysmedynskyi denys.medynskyi+abcde@gmail.com... nice try

**Comment by denys-medynskyi** [comment]
I wanted to argue about that, but then I found that Facebook doesn't allow me to register with denys.medynskyi+abcde@gmail.com

**Comment by denys-medynskyi** [comment]
verified on production
