### ISSUE TITLE
User can attend to waiting list during confirmation

### ISSUE THREAD

**Issue by sveredyuk** [pivorakmeetup/pivorak-web-app#240]

**Comment by denys-medynskyi** [comment]
If we will show `Attend` during confirmation
When this message should be visible:
```
Sorry, but application is closed. You can still use handpower and write email to us at pivorak.me@gmail.com
```
?

**Comment by sveredyuk** [comment]
We cannot resolve this issue because we don't have the possibility to send confirmations instructions to a single member.

**Comment by sveredyuk** [comment]
Closed as not required
