### ISSUE TITLE
Admin can filter email's receivers by EventFilter

### ISSUE THREAD

**Issue by sveredyuk** [pivorakmeetup/pivorak-web-app#243]

**Comment by sveredyuk** [comment]
@denys281 this task is interesting if you like js / ajax )

**Comment by denys281** [comment]
@sveredyuk I could try. It is in admin part?

**Comment by sveredyuk** [comment]
@denys281 yes, let's continue in slack. too much typing )

are you joined pivorak's slack ?

**Comment by sveredyuk** [comment]
@denys281 issue becomes outdated
