### ISSUE TITLE
Flash message after refuse confirmatrion

### ISSUE THREAD

**Issue by sveredyuk** [pivorakmeetup/pivorak-web-app#250]
It displays "See you in Friday!" but we need something else.

**Comment by denys-medynskyi** [comment]
Do you mean after user confirmation ?
Steps to reproduce for each bug would be great.

**Comment by sveredyuk** [comment]
@denysmedynskyi At event confirmation phase use can confirm (that he 100% will be) or refuse attendance. But know flash message is the same.

Reproduce:

1) create event, status: registration
2) attend to event
3) change event status to confirmation
4) confirm or refuse and will see that flash message is same for both.

Fix flash for each action (confirm / refuse)
