### ISSUE TITLE
'Reset password instructions' email received 'Change my password' link without href

### ISSUE THREAD

**Issue by slavikg** [pivorakmeetup/pivorak-web-app#252]
Yandex mail
```<a class="daria-goto-anchor" target="_blank" rel="noopener noreferrer">Change my password</a>```

**Comment by sveredyuk** [comment]
Seems like it depend on mail provider. Smb know how to fix this ?

**Comment by sveredyuk** [comment]
@slavikg please, try to remove from link everything before pivorak.com and enter again without pre-domain token.

**Comment by vova** [comment]
Although the whole reset password thing worked smoothly for me, I'd add some amount of Pivorak words into the subj and body text. Now an email with just "Reset password instructions" looks a bit anonymously :) wouldn't it better to say 'Pivorak: Reset password instructions' and 'Hello from Pivorak community, %username'?

**Comment by sveredyuk** [comment]
@vova PR with fix devise email subject welcomed
