### ISSUE TITLE
User event auto-approve email

### ISSUE THREAD

**Issue by sveredyuk** [pivorakmeetup/pivorak-web-app#256]
Send event#approved email when user was auto-approved (because verified and was free slot)

**Comment by denys-medynskyi** [comment]
If it is auto-approved maybe email should be also called `auto_approved` ?

**Comment by denys-medynskyi** [comment]
Do you mean this shit - https://github.com/pivorakmeetup/pivorak-web-app/blob/development/app/mailers/visit_request_mailer.rb#L23 ?

**Comment by sveredyuk** [comment]
@denysmedynskyi this is email. I mean flash message (controller flash)

**Comment by sveredyuk** [comment]
@denysmedynskyi Sorry, miss communication. Yes, I mean that we need send email after member was auto-approved to the event. (because of free slots and he is verified)
