### ISSUE TITLE
Increase font-size up to 1.2rem

### ISSUE THREAD

**Issue by sveredyuk** [pivorakmeetup/pivorak-web-app#260]
Recommendation from users

**Comment by oookli** [comment]
@sveredyuk we should discuss it with @yuriichaban

**Comment by sveredyuk** [comment]
Please, make decision before 1.2 release @yuriichaban @oookli @Okbil @pbilyk

**Comment by pbilyk** [comment]
I'd recommend setting the root font to 100%; then each user can increase the font size on the browser level as it suits them and the rest of the application will follow that choice as well.

Also, there is a neat trick with breakpoints for better accessibility. We can convert them from pixels to rem, and that way when the user changes font size on a browser level, the layout will also follow that change. To do this, we take 16px (default font size in most browsers) as a base value and that way our 320px breakpoint turns into 20rem. And when the user has troubles with seeing our application at that font size and increases it to 18, for example; the application reevaluates it and now breaks into mobile earlier, at 360px. That way layout does not break and also provides a better experience for navigation and usage of the site.

It's a good user-centric technique, which promotes a better inclusivity.

**Comment by skrix** [comment]
Close due to inactivity in this issue since 2017 year.
