### ISSUE TITLE
Admin members filter

### ISSUE THREAD

**Issue by sveredyuk** [pivorakmeetup/pivorak-web-app#264]
Admin wants filter members by:
- synthetic true / false
- verified true / false
- admin true / false
- speaker true / false

**Comment by denys-medynskyi** [comment]
I will implement simple toggle filters

**Comment by sveredyuk** [comment]
@denysmedynskyi Good luck

**Comment by denys-medynskyi** [comment]
Do we need admin filter ? We have only one admin - pivorak.me@gmail.com

**Comment by sveredyuk** [comment]
We can have any amount of admins
