### ISSUE TITLE
Log in as user

### ISSUE THREAD

**Issue by sveredyuk** [pivorakmeetup/pivorak-web-app#277]
according to:  https://github.com/plataformatec/devise/wiki/How-To:-Sign-in-as-another-user-if-you-are-an-admin

**Comment by denys-medynskyi** [comment]
That is cool feature

**Comment by denys281** [comment]
There are gem with this functionality https://github.com/igorkasyanchuk/any_login 

p.s  Created by my teammate)

**Comment by sveredyuk** [comment]
@denys281 @denysmedynskyi  yes, gem... But.. we are **pivorakers!**

And if some feature requires 5 lines of code, we don't need a gem.
