### ISSUE TITLE
PDF generation with visitors names

### ISSUE THREAD

**Issue by sveredyuk** [pivorakmeetup/pivorak-web-app#287]
Allow admin to generate (and print) PDF with visitors names for badges.

**Comment by floor114** [comment]
Hi. I can implement this feature.

**Comment by sveredyuk** [comment]
@floor114 Sorry, @deril already in progress

**Comment by sveredyuk** [comment]
@deril Hi, any progress with this feature? @floor114 Could do this

**Comment by deril** [comment]
I will create a pull request in a day or so
