### ISSUE TITLE
User profile management

### ISSUE THREAD

**Issue by sveredyuk** [pivorakmeetup/pivorak-web-app#31]
User can manage his/her profile:

- Change name/email/password
- Choose avatar or select use from gravatar
- Fill profile data (.. job title, company, etc.. )

**Comment by skrypalyk** [comment]
it will be mine

**Comment by sveredyuk** [comment]
@pivorak @skrypalyk discuss please with Oxana and Anna what fields we allow to fill. Maybe some hard/soft skills, programing languages or technologies, maybe allow user set number from 0 to 10 for each technology.
