### ISSUE TITLE
As a user, I want to be able to cancel an event confirmation.

### ISSUE THREAD

**Issue by DmytroLukianov** [pivorakmeetup/pivorak-web-app#388]
The user receives the email "Are you coming for sure?", After clicking on OK, he can not cancel it.

**Comment by sveredyuk** [comment]
@DmytroLukianov because the question was "are you sure".. why user clicked if he was not sure? )

I know this case, usually we send confirmations email 2-3 days before the event, and if user confirmed and then lose possibility we need a feature to manage this. 

GJ

**Comment by sveredyuk** [comment]
@DmytroLukianov hope someone picks this issue. Anyway, yours MR's welcomed.

**Comment by denys-medynskyi** [comment]
@DmytroLukianov do you mean here -> https://pivorak.com/ -> should be an ability to cancel attendance?

**Comment by sveredyuk** [comment]
I think he means cancel attendance after confirm. Yes, now we don't allow to cancel confirmation.

**Comment by denys-medynskyi** [comment]
When user is in waiting list - user should be able to cancel attendance too

**Comment by sveredyuk** [comment]
@denysmedynskyi Yes
