### ISSUE TITLE
External mail service

### ISSUE THREAD

**Issue by sveredyuk** [pivorakmeetup/pivorak-web-app#39]
Setup `Mailgun` for send emails.

**Comment by skrypalyk** [comment]
I will setup it using pivorak gmail account

**Comment by sveredyuk** [comment]
@skrypalyk no no no no. If we use just gmail account, very soon account will be banned for spam.

**Comment by skrypalyk** [comment]
@sveredyuk I meant, that I will use pivorak@gmail.com to create mandrill account

**Comment by sveredyuk** [comment]
Ok

**Comment by sveredyuk** [comment]
Ok
