### ISSUE TITLE
[Feature] Endless scroll for talks

### ISSUE THREAD

**Issue by avozniak** [pivorakmeetup/pivorak-web-app#459]
Replace the pagination to the endless scroll on talks page https://pivorak.com/talks

**Comment by ostaptan** [comment]
I can make it like this
http://railscasts.com/episodes/114-endless-page-revised

**Comment by sveredyuk** [comment]
Only if you could do this via pure-js without jquery

**Comment by ostaptan** [comment]
oh..
This changes a lot. I need to find time for this..

**Comment by sveredyuk** [comment]
@ostaptan @avozniak  Any progress of this issue? Or we can close it as redundant ?
