### ISSUE TITLE
Full text seach

### ISSUE THREAD

**Issue by sveredyuk** [pivorakmeetup/pivorak-web-app#48]
Implement `Postgres Full Text Search` for fast searching `users, events, talks`.
https://github.com/Casecommons/pg_search

**In this iteration - only for admin area.**

User - by email, full_name
Event - by title, agenda, description
Talk - by title, speaker full_name, description

**Comment by kushniryb** [comment]
@sveredyuk What about goals, shouldn't we add search by title & description?

**Comment by sveredyuk** [comment]
@kushniryb In admin area we need tool for fast search/filter for any resource. Maybe some pluggable module with configurable intrerface
