### ISSUE TITLE
[Feature] Add currency during saving new donation to the database

### ISSUE THREAD

**Issue by Sontsevolosa** [pivorakmeetup/pivorak-web-app#498]
- Add new field to the `donations` table with ` currency` name
- In the `Donation` model add validation for checking presence of this field 
- Implement saving currency during saving new donation to the database

**Comment by ostaptan** [comment]
I can look at this.

**Comment by sveredyuk** [comment]
@ostaptan go ahead

**Comment by ostaptan** [comment]
How should I get currency from liqpay? Or should I set UAH as default for now? @sveredyuk
will currency appear here https://github.com/pivorakmeetup/pivorak-web-app/blob/development/app/controllers/goals_controller.rb#L24 ?

**Comment by sveredyuk** [comment]
I am not very well qualified with liqpay merchant. You can discover this incredible world by yourself )
