### ISSUE TITLE
User slug generator

### ISSUE THREAD

**Issue by sveredyuk** [pivorakmeetup/pivorak-web-app#54]
Set user slug based on first_name and last_name.

**Example:**
```ruby
first_name: 'Volodya'
second_name: 'Sveredyuk'
slug: 'volodya-sveredyuk' # or volodya-sveredyuk-1 or -2 or -3 if duplicated
```

**Comment by denys-medynskyi** [comment]
@sveredyuk how it will be used ?

**Comment by sveredyuk** [comment]
@denysmedynskyi  show nice url -> `/members/denys.medynskyi`

**Comment by denys-medynskyi** [comment]
Should I create issue - "add page with members list" ?

**Comment by sveredyuk** [comment]
@denysmedynskyi ofc and also issues:
1. user profile visibility (maybe some users wanna hide profile from public overview)
2. users search at /members
3. user profile management: JobPosition, Company, Tech Skills, Soft Skills, Bio.. etc...

**Comment by denys-medynskyi** [comment]
@sveredyuk what do you think - should I use friendly-id gem or build slug with hands ?

**Comment by sveredyuk** [comment]
@denysmedynskyi use friendlyId, but tune it
