### ISSUE TITLE
[Feature] Add permalink to the event

### ISSUE THREAD

**Issue by nordringrayhide** [pivorakmeetup/pivorak-web-app#540]
Now it is not possible to share a link to the certain event. The only way to share info about an event is reusing one of the FB or Twitter announcement.

As a member of ruby community, I wanna have a direct permanent link to the certain event to be able to share it with my friends on the WEB

**Comment by sveredyuk** [comment]
Which exactly event you mean? Upcoming or past?

**Comment by nordringrayhide** [comment]
Any. 
As a member of Ruby community, I wanna be able to share an upcoming event link which I'ma gonna visit to
As a MoRC, I wanna share an upcoming event link to find out the opinion a friend of mine if the event is deserved to be visited.
As a MoRC, I wanna share a past event link, to have a confirmation that I was a presenter for the event in my CV e.g.
As a MoRC, I wanna share a past event link, as a reference to a some highlighted solution.

**Comment by nordringrayhide** [comment]
So it's just hard to implement? With no comment? Nice resolution. Cheers :-)
