### ISSUE TITLE
Security hole: Visit confirmation should rely on its `token`, not `id`

### ISSUE THREAD

**Issue by vlasiak** [pivorakmeetup/pivorak-web-app#545]
After user finally confirms/rejects his presence through an email, he is being signed in automatically, depending on  visit request's id and regardless its token, which is wrong.

I've managed to pick up event/visit_request pair and log in as any other user (admin, too).
Also, integration of `rack-attack` will not be amiss, imho. It'll prevent an application from brute forcing.

**Comment by vlasiak** [comment]
@floor114, why did you remove the description of the issue? Does it seem more clear to anyone now?

**Comment by floor114** [comment]
@vlasiak to prevent some attacks, because there was a lot of info how to use this hole.
