### ISSUE TITLE
User email confirmation

### ISSUE THREAD

**Issue by sveredyuk** [pivorakmeetup/pivorak-web-app#57]
Require confirm user email before any next action

**Comment by denys-medynskyi** [comment]
@sveredyuk can I close issue or it is your "thing" ?

**Comment by sveredyuk** [comment]
@skrypalyk Close

**Comment by sveredyuk** [comment]
@skrypalyk If in MR comment you mentioned "Fixed #issue_id", merging will close issue

**Comment by denys-medynskyi** [comment]
@sveredyuk ok. next time I will do it
