### ISSUE TITLE
Ability to put different marks via developer tools in admin section

### ISSUE THREAD

**Issue by ivanternovyi** [pivorakmeetup/pivorak-web-app#591]
![1](https://user-images.githubusercontent.com/22223732/41988822-f9a7794a-7a45-11e8-947c-1fc752ae7f4e.png)
![2](https://user-images.githubusercontent.com/22223732/41988823-f9cfa578-7a45-11e8-81d0-05f09ee6c01e.png)
![3](https://user-images.githubusercontent.com/22223732/41988824-f9f4f6fc-7a45-11e8-9479-7c21e69a50d0.png)
![4](https://user-images.githubusercontent.com/22223732/41988825-fa221a42-7a45-11e8-8183-e02e4e5521c4.png)

**Comment by sveredyuk** [comment]
Well done) Now waiting for fix)
