### ISSUE TITLE
[FIX] Float type for homework marks

### ISSUE THREAD

**Issue by nazik23** [pivorakmeetup/pivorak-web-app#593]
As result of using float type for homework marks we have incorrect total mark
![image](https://user-images.githubusercontent.com/27735570/42258669-8cd145b0-7f65-11e8-98ca-56867f52a766.png)
That column need to be migrated to decimal type

**Comment by sveredyuk** [comment]
@nazik23  Do you wanna fix that ? In admin area we also have this problem too.

**Comment by nazik23** [comment]
@sveredyuk yes, I want to try to fix that

**Comment by sveredyuk** [comment]
@nazik23 Go on! Good luck & Have fun
