### ISSUE TITLE
Change links YES / NO to buttons in VisitRequestMailer#confirmation

### ISSUE THREAD

**Issue by denys-medynskyi** [pivorakmeetup/pivorak-web-app#642]
At the moment our template is saved into database as markdown.
We need to add styling to those link since they are important and need to attract attention.

You need to:
- create a slim file and translate markdown into slim or add styling to markdown?(❓ I don't know is it possible )
- make links look like buttons
- YES should be green 💚
- NO should be red 🔴

**Comment by Aguardientico** [comment]
I think it is already fixed, right?

**Comment by denys-medynskyi** [comment]
Yes. Forgot to close.
