### ISSUE TITLE
Investigate donate form

### ISSUE THREAD

**Issue by denys-medynskyi** [pivorakmeetup/pivorak-web-app#658]
Sometimes when you visit https://pivorak.com/donate and click ckeckbox WayForPay widget doesn't fire and you can't donate.
Afterwards, after reload or some time you can donate.
It can be related to the thingy that WayForPay.js is loaded and we do not wait until it is loaded finally to trigger the widget.

Please, investiage - ping @denysmedynskyi or @sveredyuk

**Comment by gmile** [comment]
Ran into this very issue. Worked around by visiting https://secure.wayforpay.com/button/b644556e003e4 and donating directly on that page.

A separate issue: after donating, I was redirected to pivorak.com but got a 500 error:
![image](https://user-images.githubusercontent.com/207112/50374344-51434400-05f5-11e9-91d8-3a6ffc35998b.png)
