### ISSUE TITLE
[FIX] Group buttons on event/edit page on registration phase

### ISSUE THREAD

**Issue by denys-medynskyi** [pivorakmeetup/pivorak-web-app#674]
### Description:
- Set event in the registration phase
- Observe the buttons positioning

### Expected behavior: 
- Buttons should be responsive

### Actual behavior:
- Buttons are not responsive

Examples:
- https://pivorak.com/admin/events/pivorak-36/edit
<img width="1280" alt="screen shot 2018-12-03 at 1 06 18 pm" src="https://user-images.githubusercontent.com/5591973/49370219-3e2b0b80-f6fc-11e8-87a6-9f5972889d92.png">

Let's make buttons great again!

**Comment by Hollister009** [comment]
working on this one

**Comment by Hollister009** [comment]
Can't reproduce this issue
