### ISSUE TITLE
Deploy process

### ISSUE THREAD

**Issue by sveredyuk** [pivorakmeetup/pivorak-web-app#7]
1. Setup production ENV
2. Setup Capristano
3. Add backups system

**Comment by skrypalyk** [comment]
@sveredyuk should someone setup AWS micro instance ?

**Comment by sveredyuk** [comment]
@skrypalyk We need at least production and staging instances. Where deploy the app - please discuss with Oxana, it's also depend on monthly price

**Comment by sveredyuk** [comment]
@denysmedynskyi any chance to setup hooks for deploy staging after any merging into development branch ?

**Comment by denys-medynskyi** [comment]
@sveredyuk ok. I will work on it

**Comment by denys-medynskyi** [comment]
superadministator took a vacation, so this issue will wait
