### ISSUE TITLE
Fix coming soon page on mobile

### ISSUE THREAD

**Issue by denys-medynskyi** [pivorakmeetup/pivorak-web-app#726]
OS: iPhone 8

**Comment by denys-medynskyi** [comment]
![21a76af7-3b99-4afb-bfbb-9c355fb0f711](https://user-images.githubusercontent.com/5591973/52398170-cfce4500-2ac0-11e9-81cd-6b2cfb1b3bb2.png)

**Comment by aleksacastle** [comment]
+ Android 9
