### ISSUE TITLE
[UI] Fix space between items in dropdown

### ISSUE THREAD

**Issue by Sontsevolosa** [pivorakmeetup/pivorak-web-app#762]
How to reproduce:

1. Place cursor on link with your user name in the top vertical menu.
2. You will see dropdown under your user name. The first item in this dropdown will partly cover your user name.

Please, change space between items in dropdown.

Used browser: Google Chrome

Attached screenshot:
<img width="304" alt="Screen Shot 2019-04-10 at 6 10 15 PM" src="https://user-images.githubusercontent.com/15029139/55892543-276f5680-5bbf-11e9-8ae6-1b0b15f08d0d.png">

**Comment by LAnastasiia** [comment]
I take it :)
