### ISSUE TITLE
Make slides more visible on the website

### ISSUE THREAD

**Issue by denys-medynskyi** [pivorakmeetup/pivorak-web-app#815]
Currently on https://pivorak.com/talks/some-strange-stories-about-mocks you can click `Watch slideshare`.

Users don't see this - discussion in Slack
https://pivorak.slack.com/archives/C1AJ039FA/p1568367134086300

Think! how to make it more visible.

For example:
- Put the `SLIDES` link near the title, make it big.
- Maybe add good looking icon

**Comment by oxanayoxana** [comment]
Will that be ok for now - https://prnt.sc/pb52yp ?
And when hovered over - 
![Screen Shot 2019-09-26 at 10 40 47](https://user-images.githubusercontent.com/17854794/65668602-af043100-e04a-11e9-8142-27d29338c226.png)

Also, maybe leave this issue open, for smb else to improve it more...
