### ISSUE TITLE
Markdown editor

### ISSUE THREAD

**Issue by sveredyuk** [pivorakmeetup/pivorak-web-app#82]
- Add markdown editor https://simplemde.com/
- Implement possibility attach it to any text field
- Add it to event.agenda text field

**Comment by denys-medynskyi** [comment]
@sveredyuk should I use [gem](https://github.com/KHN190/simplemde-rails) for this ?

**Comment by sveredyuk** [comment]
@denysmedynskyi idk. Maybe the best way will be just add it to vendor like min.js
