### ISSUE TITLE
[UI] Fix edit button on talk show page

### ISSUE THREAD

**Issue by skrix** [pivorakmeetup/pivorak-web-app#822]
### Expected behavior:
- Open a talk show page as an admin
- Observe the edit button link
- Click on the `Edit` button (not on the text with a link on it)
- Edit page of current talk is opened

### Current behavior:
- Open a talk show page as an admin
- Observe the edit button link
- Click on the `Edit` button (not on the text with a link on it)
- `Nothing happens, the button is not clickable`

##### Proposed solution: Add link also to the button

![image](https://user-images.githubusercontent.com/16745269/66565604-911aee00-eb6b-11e9-962e-40d194b6b90b.png)

**Comment by oxanayoxana** [comment]
@skrix  can take it now

**Comment by oxanayoxana** [comment]
Pls, take a look at pr https://github.com/pivorakmeetup/pivorak-web-app/pull/829
