### ISSUE TITLE
[UI] Improve `watch slideshare` link

### ISSUE THREAD

**Issue by skrix** [pivorakmeetup/pivorak-web-app#824]
### Expected behavior:
- Open a talk show page as an admin
- Observe the `Watch slides` button link styled like `Edit button` with bold text

### Current behavior:
- Open a talk show page as an admin
- Observe the `watch slideshare` link style

![image](https://user-images.githubusercontent.com/16745269/66565604-911aee00-eb6b-11e9-962e-40d194b6b90b.png)

**Comment by TuxujPes** [comment]
I'll grab this one!

**Comment by tkharuk** [comment]
I'll grab this one!
