### ISSUE TITLE
[UI] Show active selected page at primary navigation

### ISSUE THREAD

**Issue by skrix** [pivorakmeetup/pivorak-web-app#826]
### Expected behavior:
- Open a pivorak site
- Click on the navigation bar item
- The selected page is opened and the navbar item is highlighted

### Current behavior:
- Open a pivorak site
- Click on the navigation bar item
- The selected page is opened but the navbar item is not highlighted

#### Example: Talks page opened but the option in the navbar is not highlighted

![image](https://user-images.githubusercontent.com/16745269/66628597-f4f2f480-ec07-11e9-88d4-ce7266d08093.png)

**Comment by shankar524** [comment]
@skrix  Can I work this issue?

**Comment by skrix** [comment]
@shankar524 yes, let's do it!)
