### ISSUE TITLE
[Improvement] Add guide for speakers

### ISSUE THREAD

**Issue by aleksacastle** [pivorakmeetup/pivorak-web-app#827]
**Task:** Add Guide for speakers
**Where:** Info -> Guide for speakers
**Example:**  [Code of conduct](https://pivorak.com/code-of-conduct)
**Additional requirements:** Preserve markdown in the document and table of content

**Comment by shankar524** [comment]
Can I work on this issue?

**Comment by shankar524** [comment]
@skrix Could you please review [this gist](https://gist.github.com/shankar524/58be2954383446788f3261033762ff74), I think this should help.

**Comment by aleksacastle** [comment]
@shankar524 I would really appreciate if you add a source to this gist: #pivorak and @aleksacastle  as an author. Thanks

**Comment by shankar524** [comment]
@aleksacastle 
Do you mean adding the link to the document to the gist comments and mention you as the author in it?

**Comment by aleksacastle** [comment]
@shankar524 add source and author to the text of git itself.

**Comment by skrix** [comment]
@shankar524 I really confused with your gist because it's just a copy-paste from @aleksacastle document, so find another issue please and stop stilling somebody's work as a way to complete hacktoberfest, read the policies on the hacktoberfest site. Thanks!

**Comment by shankar524** [comment]
@skrix sorry for the confusion. I was hoping to format the Google Doc to Markdown that would help others to copy the markdown text and insert into the Page Model.
I need to mention the credit to Pivorak and I will. But I am confused on giving author in Gist file.

I can remove the gist file if you ask me.

**Comment by skrix** [comment]
@shankar524 thanks, for your effort and sorry for the confusion, the issue has some drawbacks in the description, the reporter will fix it as @aleksacastle has more context of the task, so have a nice Hacktoberfest Journey and thanks for your time!

**Comment by shankar524** [comment]
@skrix I have mentioned author name and source of document from which gist was prepared. you may use that gist in future. (Will delete if you insist). Thanks for clarifying and happy Hacktoberfest.
