### ISSUE TITLE
Баг на сторінці списку тестових завдань

### ISSUE THREAD

**Issue by denys-medynskyi** [pivorakmeetup/pivorak-web-app#898]
- Visit https://pivorak.com/admin/courses/seasons/pivorak-ruby-summer-course-2020/test_task
- Тестова завдання призначене на мене
- Справа нічого не відобажено
**Очікування**: має бути відображено що призначене на мене

<img width="1037" alt="Screenshot 2020-04-24 at 21 22 23" src="https://user-images.githubusercontent.com/5591973/80244572-d4edc480-8671-11ea-9859-c8716d2f4b4c.png">

**Comment by sveredyuk** [comment]
Ця бага через те, що коли зберігаєш ноутси воно ставить статус `nil`

**Comment by sveredyuk** [comment]
@deny7ko глянь пр пліз, бо треба змержити
