### ISSUE TITLE
Setup CodeClimat

### ISSUE THREAD

**Issue by sveredyuk** [pivorakmeetup/pivorak-web-app#9]
1. Add CodeClimat
2. Add badge to README.md

**Comment by nickKolya** [comment]
Can pick up this one

**Comment by sveredyuk** [comment]
@nickKolya go ahead!

**Comment by nickKolya** [comment]
@sveredyuk is #22 PR really have any relation to this issue or it is just typo?

**Comment by sveredyuk** [comment]
@nickKolya github is very strange with this `#` ids. Idk.
