### ISSUE TITLE
pivorak-ruby-summer-course-2020 "status": 500

### ISSUE THREAD

**Issue by alekseiismirnov** [pivorakmeetup/pivorak-web-app#901]
по адресі
https://pivorak.com/courses/seasons/pivorak-ruby-summer-course-2020
пуста сторінка

[pivorak.com.har.txt](https://github.com/pivorakmeetup/pivorak-web-app/files/4567061/pivorak.com.har.txt)

**Comment by sveredyuk** [comment]
@alekseiismirnov А який емейл ви використовуєте для логіну на сайт?

**Comment by skrix** [comment]
@sveredyuk проблема не в мейлі, а в тому, що курси уже в стадії відбору, а лінк на подачу заявки, просто там немає редіректу, що реєстрація вже закрита.

**Comment by sveredyuk** [comment]
@skrix Воно для різних студентів по-різному поводиться. 500-ка через те, що ми якийсь кейс не закрили

**Comment by alekseiismirnov** [comment]
@skrix ясно, сорян.  зі строків бачив тільки  продовжений дедлайн для сдачі тестового завдання, до завтра

**Comment by sveredyuk** [comment]
@alekseiismirnov ми закрили прийом тестових вчора (1-го травня).

**Comment by alekseiismirnov** [comment]
тут бачив
https://dou.ua/calendar/31782/

**Comment by sveredyuk** [comment]
@alekseiismirnov Значить у нас міскомунікейшин. Я відкрию форму для злачі тестових. Можете спробувати ще раз?

**Comment by alekseiismirnov** [comment]
Все працює.
