### ISSUE TITLE
Visited events at member's page

### ISSUE THREAD

**Issue by sveredyuk** [pivorakmeetup/pivorak-web-app#97]
Show which event's member visited

**Comment by denys-medynskyi** [comment]
oxana said, that  admin should be able to mark someone who didn't show up. I suggest to create issue - Admin should be able to mark attendee did not show up. What do you think @sveredyuk ?

**Comment by sveredyuk** [comment]
Yes, admin will check all who really come to the event by #98 
Everyone else will get 'miss'

**Comment by denys-medynskyi** [comment]
so this issue will wait untile #98 is done
